# Generated by Django 5.0.6 on 2024-06-07 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategorySigns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'category_signs',
            },
        ),
        migrations.CreateModel(
            name='RoadSigns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('video', models.FileField(blank=True, null=True, upload_to='videos')),
                ('audio', models.FileField(blank=True, null=True, upload_to='audio')),
                ('dock', models.FileField(blank=True, null=True, upload_to='dock')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sign.categorysigns')),
            ],
            options={
                'db_table': 'road_signs',
            },
        ),
    ]
